// Gera themes/toski-dark-color-theme.json e themes/toski-light-color-theme.json
// a partir de scripts/palette.mjs.  Uso: node scripts/build-themes.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { dark, light } from './palette.mjs';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

function colors(p) {
  const T = p.bg + '00'; // transparente, sem usar preto puro
  const a = p.alpha;
  const s = p.syntax;
  const isDark = p.type === 'dark';
  return {
    // Base
    foreground: p.fg,
    descriptionForeground: p.fg2,
    disabledForeground: p.lineNumber,
    errorForeground: p.error,
    focusBorder: p.accent,
    'icon.foreground': p.fg2,
    'selection.background': p.selection,
    'widget.border': p.border,
    'widget.shadow': a.shadow,
    'scrollbar.shadow': a.shadow,
    'sash.hoverBorder': p.accent,
    'textLink.foreground': p.link,
    'textLink.activeForeground': p.link,
    'textBlockQuote.background': p.side,
    'textBlockQuote.border': p.border,
    'textCodeBlock.background': p.side,
    'textPreformat.foreground': s.string,
    'textPreformat.background': p.side,
    'textSeparator.foreground': p.border,

    // Title bar
    'titleBar.activeBackground': p.panel,
    'titleBar.activeForeground': p.fg,
    'titleBar.inactiveBackground': p.panel,
    'titleBar.inactiveForeground': p.fg2,
    'titleBar.border': p.border,

    // Activity bar
    'activityBar.background': p.panel,
    'activityBar.foreground': p.fg,
    'activityBar.inactiveForeground': p.fg2,
    'activityBar.border': p.border,
    'activityBar.activeBorder': p.accent,
    'activityBar.activeBackground': T,
    'activityBarBadge.background': p.accent,
    'activityBarBadge.foreground': p.onAccent,
    'activityBarTop.foreground': p.fg,
    'activityBarTop.inactiveForeground': p.fg2,
    'activityBarTop.activeBorder': p.accent,
    'activityBarTop.background': p.panel,

    // Side bar
    'sideBar.background': p.side,
    'sideBar.foreground': p.fg,
    'sideBar.border': p.border,
    'sideBarTitle.foreground': p.fg,
    'sideBarSectionHeader.background': p.side,
    'sideBarSectionHeader.foreground': p.fg,
    'sideBarSectionHeader.border': p.border,
    'sideBar.dropBackground': a.hover,

    // Lists / trees
    'list.activeSelectionBackground': p.listActive,
    'list.activeSelectionForeground': p.fg,
    'list.activeSelectionIconForeground': p.fg,
    'list.inactiveSelectionBackground': a.inactiveList,
    'list.inactiveSelectionForeground': p.fg,
    'list.hoverBackground': a.hover,
    'list.hoverForeground': p.fg,
    'list.focusBackground': p.listActive,
    'list.focusForeground': p.fg,
    'list.focusOutline': p.accent,
    'list.inactiveFocusOutline': p.border,
    'list.highlightForeground': p.link,
    'list.focusHighlightForeground': p.link,
    'list.errorForeground': p.error,
    'list.warningForeground': p.warning,
    'list.invalidItemForeground': p.error,
    'list.deemphasizedForeground': p.fg2,
    'list.dropBackground': a.hover,
    'listFilterWidget.background': p.side,
    'listFilterWidget.outline': p.accent,
    'listFilterWidget.noMatchesOutline': p.error,
    'tree.indentGuidesStroke': p.border,
    'tree.inactiveIndentGuidesStroke': p.border,

    // Editor groups & tabs
    'editorGroup.border': p.border,
    'editorGroup.dropBackground': a.hover,
    'editorGroupHeader.tabsBackground': p.panel,
    'editorGroupHeader.tabsBorder': p.border,
    'editorGroupHeader.noTabsBackground': p.panel,
    'tab.activeBackground': p.bg,
    'tab.activeForeground': p.fg,
    'tab.activeBorderTop': p.accent,
    'tab.activeBorder': p.bg,
    'tab.inactiveBackground': p.panel,
    'tab.inactiveForeground': p.fg2,
    'tab.hoverBackground': p.bg,
    'tab.hoverForeground': p.fg,
    'tab.unfocusedActiveBackground': p.bg,
    'tab.unfocusedActiveForeground': p.fg2,
    'tab.unfocusedActiveBorderTop': p.border,
    'tab.unfocusedInactiveForeground': p.fg2,
    'tab.border': p.border,
    'tab.lastPinnedBorder': p.border,
    'tab.activeModifiedBorder': p.accent,
    'tab.inactiveModifiedBorder': p.border,
    'tab.selectedBackground': p.bg,
    'tab.selectedForeground': p.fg,
    'tab.selectedBorderTop': p.accent,

    // Breadcrumbs
    'breadcrumb.background': p.bg,
    'breadcrumb.foreground': p.fg2,
    'breadcrumb.focusForeground': p.fg,
    'breadcrumb.activeSelectionForeground': p.fg,
    'breadcrumbPicker.background': p.side,

    // Editor
    'editor.background': p.bg,
    'editor.foreground': p.fg,
    'editorLineNumber.foreground': p.lineNumber,
    'editorLineNumber.activeForeground': p.lineNumberActive,
    'editorLineNumber.dimmedForeground': p.lineNumber,
    'editorCursor.foreground': p.cursor,
    'editorCursor.background': p.bg,
    'editor.selectionBackground': p.selection,
    'editor.inactiveSelectionBackground': a.inactiveSelection,
    'editor.selectionHighlightBackground': a.selectionHighlight,
    'editor.selectionHighlightBorder': T,
    'editor.wordHighlightBackground': a.wordHighlight,
    'editor.wordHighlightStrongBackground': a.wordHighlightStrong,
    'editor.wordHighlightBorder': T,
    'editor.findMatchBackground': a.findMatch,
    'editor.findMatchBorder': p.accent,
    'editor.findMatchHighlightBackground': a.findMatchHighlight,
    'editor.findMatchHighlightBorder': T,
    'editor.findRangeHighlightBackground': a.findRange,
    'editor.rangeHighlightBackground': a.rangeHighlight,
    'editor.lineHighlightBackground': p.lineHighlight,
    'editor.lineHighlightBorder': p.lineHighlight,
    'editor.hoverHighlightBackground': a.wordHighlight,
    'editor.linkedEditingBackground': a.wordHighlight,
    'editor.foldBackground': a.rangeHighlight,
    'editorLink.activeForeground': p.link,
    'editorWhitespace.foreground': p.border,
    'editorIndentGuide.background1': p.border,
    'editorIndentGuide.activeBackground1': p.lineNumber,
    'editorRuler.foreground': p.border,
    'editorCodeLens.foreground': p.fg2,
    'editorInlayHint.foreground': p.fg2,
    'editorInlayHint.background': T,
    'editorInlayHint.typeForeground': p.fg2,
    'editorInlayHint.parameterForeground': p.fg2,
    'editorLightBulb.foreground': p.warning,
    'editorLightBulbAutoFix.foreground': p.info,
    'editorStickyScroll.background': p.bg,
    'editorStickyScrollHover.background': p.lineHighlight,
    'editorStickyScroll.shadow': a.shadow,

    // Bracket match & pair colorization
    'editorBracketMatch.background': a.bracketMatch,
    'editorBracketMatch.border': p.accent,
    'editorBracketHighlight.foreground1': s.keyword,
    'editorBracketHighlight.foreground2': s.property,
    'editorBracketHighlight.foreground3': s.type,
    'editorBracketHighlight.foreground4': s.keyword,
    'editorBracketHighlight.foreground5': s.property,
    'editorBracketHighlight.foreground6': s.type,
    'editorBracketHighlight.unexpectedBracket.foreground': p.error,
    'editorBracketPairGuide.activeBackground1': s.keyword,
    'editorBracketPairGuide.activeBackground2': s.property,
    'editorBracketPairGuide.activeBackground3': s.type,

    // Gutter
    'editorGutter.background': p.bg,
    'editorGutter.addedBackground': p.git.added,
    'editorGutter.modifiedBackground': p.git.modified,
    'editorGutter.deletedBackground': p.git.deleted,
    'editorGutter.foldingControlForeground': p.fg2,
    'editorGutter.commentRangeForeground': p.lineNumber,

    // Diagnostics
    'editorError.foreground': p.error,
    'editorError.border': T,
    'editorWarning.foreground': p.warning,
    'editorWarning.border': T,
    'editorInfo.foreground': p.info,
    'editorInfo.border': T,
    'editorHint.foreground': p.success,
    'problemsErrorIcon.foreground': p.error,
    'problemsWarningIcon.foreground': p.warning,
    'problemsInfoIcon.foreground': p.info,

    // Overview ruler
    'editorOverviewRuler.border': p.border,
    'editorOverviewRuler.background': p.bg,
    'editorOverviewRuler.findMatchForeground': p.accent,
    'editorOverviewRuler.selectionHighlightForeground': p.selection,
    'editorOverviewRuler.wordHighlightForeground': s.type,
    'editorOverviewRuler.bracketMatchForeground': p.accent,
    'editorOverviewRuler.errorForeground': p.error,
    'editorOverviewRuler.warningForeground': p.warning,
    'editorOverviewRuler.infoForeground': p.info,
    'editorOverviewRuler.addedForeground': p.git.added,
    'editorOverviewRuler.modifiedForeground': p.git.modified,
    'editorOverviewRuler.deletedForeground': p.git.deleted,

    // Minimap
    'minimap.background': p.bg,
    'minimap.findMatchHighlight': p.accent,
    'minimap.selectionHighlight': p.selection,
    'minimap.errorHighlight': p.error,
    'minimap.warningHighlight': p.warning,
    'minimapGutter.addedBackground': p.git.added,
    'minimapGutter.modifiedBackground': p.git.modified,
    'minimapGutter.deletedBackground': p.git.deleted,
    'minimapSlider.background': a.hover,
    'minimapSlider.hoverBackground': p.listActive,
    'minimapSlider.activeBackground': p.selection,

    // Scrollbar
    'scrollbarSlider.background': a.hover,
    'scrollbarSlider.hoverBackground': p.listActive,
    'scrollbarSlider.activeBackground': p.selection,

    // Widgets
    'editorWidget.background': p.side,
    'editorWidget.foreground': p.fg,
    'editorWidget.border': p.border,
    'editorWidget.resizeBorder': p.accent,
    'editorHoverWidget.background': p.side,
    'editorHoverWidget.foreground': p.fg,
    'editorHoverWidget.border': p.border,
    'editorHoverWidget.highlightForeground': p.link,
    'editorHoverWidget.statusBarBackground': p.side,
    'editorSuggestWidget.background': p.side,
    'editorSuggestWidget.foreground': p.fg,
    'editorSuggestWidget.border': p.border,
    'editorSuggestWidget.selectedBackground': p.listActive,
    'editorSuggestWidget.selectedForeground': p.fg,
    'editorSuggestWidget.highlightForeground': p.link,
    'editorSuggestWidget.focusHighlightForeground': p.link,
    'editorSuggestWidgetStatus.foreground': p.fg2,
    'editorMarkerNavigation.background': p.side,
    'editorMarkerNavigationError.background': p.error,
    'editorMarkerNavigationWarning.background': p.warning,
    'editorMarkerNavigationInfo.background': p.info,
    'debugExceptionWidget.background': p.side,
    'debugExceptionWidget.border': p.error,

    // Peek view
    'peekView.border': p.accent,
    'peekViewTitle.background': p.panel,
    'peekViewTitleLabel.foreground': p.fg,
    'peekViewTitleDescription.foreground': p.fg2,
    'peekViewEditor.background': p.side,
    'peekViewEditor.matchHighlightBackground': a.findMatch,
    'peekViewEditorGutter.background': p.side,
    'peekViewResult.background': p.panel,
    'peekViewResult.fileForeground': p.fg,
    'peekViewResult.lineForeground': p.fg2,
    'peekViewResult.matchHighlightBackground': a.findMatchHighlight,
    'peekViewResult.selectionBackground': p.listActive,
    'peekViewResult.selectionForeground': p.fg,

    // Diff editor
    'diffEditor.insertedLineBackground': a.diffInsertedLine,
    'diffEditor.insertedTextBackground': a.diffInsertedText,
    'diffEditor.removedLineBackground': a.diffRemovedLine,
    'diffEditor.removedTextBackground': a.diffRemovedText,
    'diffEditor.border': p.border,
    'diffEditor.diagonalFill': p.border,
    'diffEditorGutter.insertedLineBackground': a.diffInsertedText,
    'diffEditorGutter.removedLineBackground': a.diffRemovedText,
    'diffEditorOverview.insertedForeground': p.git.added,
    'diffEditorOverview.removedForeground': p.git.deleted,
    'multiDiffEditor.headerBackground': p.panel,
    'multiDiffEditor.border': p.border,

    // Merge conflicts
    'merge.currentHeaderBackground': a.mergeCurrent,
    'merge.currentContentBackground': a.diffInsertedLine,
    'merge.incomingHeaderBackground': a.mergeIncoming,
    'merge.incomingContentBackground': a.wordHighlight,
    'merge.commonHeaderBackground': a.mergeCommon,
    'merge.commonContentBackground': a.rangeHighlight,
    'merge.border': p.border,
    'editorOverviewRuler.currentContentForeground': p.git.added,
    'editorOverviewRuler.incomingContentForeground': p.info,
    'editorOverviewRuler.commonContentForeground': p.fg2,

    // Git decorations
    'gitDecoration.addedResourceForeground': p.git.added,
    'gitDecoration.modifiedResourceForeground': p.git.modified,
    'gitDecoration.deletedResourceForeground': p.git.deleted,
    'gitDecoration.renamedResourceForeground': p.git.renamed,
    'gitDecoration.untrackedResourceForeground': p.git.untracked,
    'gitDecoration.ignoredResourceForeground': p.git.ignored,
    'gitDecoration.conflictingResourceForeground': p.git.conflict,
    'gitDecoration.submoduleResourceForeground': p.git.submodule,
    'gitDecoration.stageModifiedResourceForeground': p.git.modified,
    'gitDecoration.stageDeletedResourceForeground': p.git.deleted,
    'scmGraph.historyItemHoverLabelForeground': p.onAccent,
    'scmGraph.foreground1': s.keyword,
    'scmGraph.foreground2': s.type,
    'scmGraph.foreground3': s.string,
    'scmGraph.foreground4': s.property,
    'scmGraph.foreground5': s.number,

    // Inputs & controls
    'input.background': p.type === 'dark' ? p.panel : p.bg,
    'input.foreground': p.fg,
    'input.border': p.border,
    'input.placeholderForeground': p.fg2,
    'inputOption.activeBackground': p.listActive,
    'inputOption.activeBorder': p.accent,
    'inputOption.activeForeground': p.fg,
    'inputValidation.errorBackground': p.side,
    'inputValidation.errorBorder': p.error,
    'inputValidation.errorForeground': p.fg,
    'inputValidation.warningBackground': p.side,
    'inputValidation.warningBorder': p.warning,
    'inputValidation.warningForeground': p.fg,
    'inputValidation.infoBackground': p.side,
    'inputValidation.infoBorder': p.info,
    'inputValidation.infoForeground': p.fg,
    'dropdown.background': p.type === 'dark' ? p.panel : p.bg,
    'dropdown.listBackground': p.side,
    'dropdown.foreground': p.fg,
    'dropdown.border': p.border,
    'checkbox.background': p.type === 'dark' ? p.panel : p.bg,
    'checkbox.foreground': p.fg,
    'checkbox.border': p.border,
    'checkbox.selectBackground': p.side,
    'radio.activeBackground': p.listActive,
    'radio.activeForeground': p.fg,
    'radio.activeBorder': p.accent,
    'radio.inactiveForeground': p.fg2,
    'radio.inactiveBorder': p.border,
    'toolbar.hoverBackground': a.hover,
    'toolbar.activeBackground': p.listActive,

    // Buttons & badges
    'button.background': p.accent,
    'button.foreground': p.onAccent,
    'button.hoverBackground': isDark ? s.function : '#994C1C',
    'button.border': T,
    'button.separator': p.onAccent + '66',
    'button.secondaryBackground': p.listActive,
    'button.secondaryForeground': p.fg,
    'button.secondaryHoverBackground': p.selection,
    'badge.background': p.accent,
    'badge.foreground': p.onAccent,
    'progressBar.background': p.accent,
    'extensionButton.prominentBackground': p.accent,
    'extensionButton.prominentForeground': p.onAccent,
    'extensionButton.prominentHoverBackground': isDark ? s.function : '#994C1C',
    'extensionButton.background': p.accent,
    'extensionButton.foreground': p.onAccent,
    'extensionButton.hoverBackground': isDark ? s.function : '#994C1C',
    'extensionBadge.remoteBackground': p.accent,
    'extensionBadge.remoteForeground': p.onAccent,
    'extensionIcon.starForeground': p.warning,
    'extensionIcon.verifiedForeground': p.link,
    'keybindingLabel.background': p.listActive,
    'keybindingLabel.foreground': p.fg,
    'keybindingLabel.border': p.border,
    'keybindingLabel.bottomBorder': p.border,

    // Menus & quick input
    'menubar.selectionBackground': a.hover,
    'menubar.selectionForeground': p.fg,
    'menubar.selectionBorder': T,
    'menu.background': p.side,
    'menu.foreground': p.fg,
    'menu.border': p.border,
    'menu.selectionBackground': p.listActive,
    'menu.selectionForeground': p.fg,
    'menu.separatorBackground': p.border,
    'quickInput.background': p.side,
    'quickInput.foreground': p.fg,
    'quickInputTitle.background': p.panel,
    'quickInputList.focusBackground': p.listActive,
    'quickInputList.focusForeground': p.fg,
    'quickInputList.focusIconForeground': p.fg,
    'pickerGroup.border': p.border,
    'pickerGroup.foreground': p.link,
    'commandCenter.background': p.side,
    'commandCenter.foreground': p.fg,
    'commandCenter.activeBackground': p.listActive,
    'commandCenter.activeForeground': p.fg,
    'commandCenter.border': p.border,
    'commandCenter.inactiveForeground': p.fg2,

    // Panel
    'panel.background': p.bg,
    'panel.border': p.border,
    'panel.dropBorder': p.accent,
    'panelTitle.activeForeground': p.fg,
    'panelTitle.activeBorder': p.accent,
    'panelTitle.inactiveForeground': p.fg2,
    'panelInput.border': p.border,
    'panelSection.border': p.border,
    'panelSectionHeader.background': p.side,
    'panelSectionHeader.foreground': p.fg,
    'outputView.background': p.bg,

    // Status bar (discreta; fica ferrugem só durante o debug)
    'statusBar.background': p.statusBar.bg,
    'statusBar.foreground': p.statusBar.fg,
    'statusBar.border': p.statusBar.border,
    'statusBar.focusBorder': p.accent,
    'statusBar.noFolderBackground': p.statusBar.bg,
    'statusBar.noFolderForeground': p.statusBar.fg,
    'statusBar.noFolderBorder': p.statusBar.border,
    'statusBar.debuggingBackground': p.status,
    'statusBar.debuggingForeground': p.onStatus,
    'statusBar.debuggingBorder': p.status,
    'statusBarItem.hoverBackground': p.statusBar.hover,
    'statusBarItem.hoverForeground': p.fg,
    'statusBarItem.activeBackground': p.statusBar.hover,
    'statusBarItem.focusBorder': p.accent,
    'statusBarItem.remoteBackground': p.statusBar.bg,
    'statusBarItem.remoteForeground': p.statusBar.remote,
    'statusBarItem.remoteHoverBackground': p.statusBar.hover,
    'statusBarItem.remoteHoverForeground': p.fg,
    'statusBarItem.prominentBackground': p.statusBar.hover,
    'statusBarItem.prominentForeground': p.fg,
    'statusBarItem.prominentHoverBackground': p.listActive,
    'statusBarItem.errorBackground': p.statusBar.bg,
    'statusBarItem.errorForeground': p.error,
    'statusBarItem.errorHoverBackground': p.statusBar.hover,
    'statusBarItem.warningBackground': p.statusBar.bg,
    'statusBarItem.warningForeground': p.warning,
    'statusBarItem.warningHoverBackground': p.statusBar.hover,
    'statusBarItem.compactHoverBackground': p.statusBar.hover,

    // Notifications
    'notificationCenter.border': p.border,
    'notificationCenterHeader.background': p.panel,
    'notificationCenterHeader.foreground': p.fg,
    'notificationToast.border': p.border,
    'notifications.background': p.side,
    'notifications.foreground': p.fg,
    'notifications.border': p.border,
    'notificationLink.foreground': p.link,
    'notificationsErrorIcon.foreground': p.error,
    'notificationsWarningIcon.foreground': p.warning,
    'notificationsInfoIcon.foreground': p.info,

    // Terminal (igual ao iTerm2)
    'terminal.background': p.terminal.bg,
    'terminal.foreground': p.terminal.fg,
    'terminal.border': p.border,
    'terminal.selectionBackground': p.terminal.selection,
    'terminal.inactiveSelectionBackground': a.inactiveSelection,
    'terminal.findMatchBackground': a.findMatch,
    'terminal.findMatchHighlightBackground': a.findMatchHighlight,
    'terminalCursor.foreground': p.terminal.cursor,
    'terminalCursor.background': p.terminal.cursorText,
    'terminal.ansiBlack': p.ansi.black,
    'terminal.ansiRed': p.ansi.red,
    'terminal.ansiGreen': p.ansi.green,
    'terminal.ansiYellow': p.ansi.yellow,
    'terminal.ansiBlue': p.ansi.blue,
    'terminal.ansiMagenta': p.ansi.magenta,
    'terminal.ansiCyan': p.ansi.cyan,
    'terminal.ansiWhite': p.ansi.white,
    'terminal.ansiBrightBlack': p.ansi.brightBlack,
    'terminal.ansiBrightRed': p.ansi.brightRed,
    'terminal.ansiBrightGreen': p.ansi.brightGreen,
    'terminal.ansiBrightYellow': p.ansi.brightYellow,
    'terminal.ansiBrightBlue': p.ansi.brightBlue,
    'terminal.ansiBrightMagenta': p.ansi.brightMagenta,
    'terminal.ansiBrightCyan': p.ansi.brightCyan,
    'terminal.ansiBrightWhite': p.ansi.brightWhite,
    'terminalCommandDecoration.defaultBackground': p.lineNumber,
    'terminalCommandDecoration.successBackground': p.success,
    'terminalCommandDecoration.errorBackground': p.error,
    'terminalOverviewRuler.cursorForeground': p.cursor,
    'terminalOverviewRuler.findMatchForeground': p.accent,
    'terminal.dropBackground': a.hover,
    'terminalStickyScroll.background': p.bg,
    'ports.iconRunningProcessForeground': p.success,

    // Debug
    'debugToolBar.background': p.side,
    'debugToolBar.border': p.border,
    'debugIcon.breakpointForeground': p.error,
    'debugIcon.breakpointDisabledForeground': p.lineNumber,
    'debugIcon.breakpointUnverifiedForeground': p.fg2,
    'debugIcon.startForeground': p.success,
    'debugIcon.pauseForeground': p.info,
    'debugIcon.stopForeground': p.error,
    'debugIcon.disconnectForeground': p.error,
    'debugIcon.restartForeground': p.success,
    'debugIcon.stepOverForeground': p.info,
    'debugIcon.stepIntoForeground': p.info,
    'debugIcon.stepOutForeground': p.info,
    'debugIcon.continueForeground': p.info,
    'debugConsole.infoForeground': p.info,
    'debugConsole.warningForeground': p.warning,
    'debugConsole.errorForeground': p.error,
    'debugConsole.sourceForeground': p.fg2,
    'debugConsoleInputIcon.foreground': p.accent,
    'debugTokenExpression.name': s.property,
    'debugTokenExpression.value': p.fg,
    'debugTokenExpression.string': s.string,
    'debugTokenExpression.boolean': s.number,
    'debugTokenExpression.number': s.number,
    'debugTokenExpression.error': p.error,
    'editor.stackFrameHighlightBackground': a.findMatchHighlight,
    'editor.focusedStackFrameHighlightBackground': a.diffInsertedText,

    // Settings, welcome, walkthrough
    'settings.headerForeground': p.fg,
    'settings.modifiedItemIndicator': p.accent,
    'settings.focusedRowBackground': a.hover,
    'settings.rowHoverBackground': a.hover,
    'settings.focusedRowBorder': p.accent,
    'settings.dropdownBackground': p.type === 'dark' ? p.panel : p.bg,
    'settings.dropdownBorder': p.border,
    'settings.checkboxBackground': p.type === 'dark' ? p.panel : p.bg,
    'settings.checkboxBorder': p.border,
    'settings.textInputBackground': p.type === 'dark' ? p.panel : p.bg,
    'settings.textInputBorder': p.border,
    'settings.numberInputBackground': p.type === 'dark' ? p.panel : p.bg,
    'settings.numberInputBorder': p.border,
    'welcomePage.background': p.bg,
    'welcomePage.tileBackground': p.side,
    'welcomePage.tileHoverBackground': p.listActive,
    'welcomePage.tileBorder': p.border,
    'welcomePage.progress.foreground': p.accent,
    'walkThrough.embeddedEditorBackground': p.side,
    'walkthrough.stepTitle.foreground': p.fg,

    // Chat / inline chat
    'chat.requestBackground': p.side,
    'chat.requestBorder': p.border,
    'chat.slashCommandBackground': p.listActive,
    'chat.slashCommandForeground': p.link,
    'chat.avatarBackground': p.listActive,
    'chat.avatarForeground': p.fg,
    'inlineChat.background': p.side,
    'inlineChat.border': p.border,
    'inlineChatInput.background': p.type === 'dark' ? p.panel : p.bg,
    'inlineChatInput.border': p.border,

    // Misc
    'banner.background': p.listActive,
    'banner.foreground': p.fg,
    'banner.iconForeground': p.accent,
    'charts.foreground': p.fg,
    'charts.lines': p.fg2,
    'charts.red': p.ansi.red,
    'charts.blue': p.ansi.blue,
    'charts.yellow': p.ansi.yellow,
    'charts.orange': p.accent,
    'charts.green': p.ansi.green,
    'charts.purple': p.ansi.magenta,
    'symbolIcon.classForeground': s.type,
    'symbolIcon.interfaceForeground': s.type,
    'symbolIcon.structForeground': s.type,
    'symbolIcon.enumeratorForeground': s.type,
    'symbolIcon.enumeratorMemberForeground': s.number,
    'symbolIcon.constantForeground': s.number,
    'symbolIcon.functionForeground': s.function,
    'symbolIcon.methodForeground': s.function,
    'symbolIcon.constructorForeground': s.function,
    'symbolIcon.propertyForeground': s.property,
    'symbolIcon.fieldForeground': s.property,
    'symbolIcon.variableForeground': p.fg,
    'symbolIcon.keywordForeground': s.keyword,
    'symbolIcon.stringForeground': s.string,
    'symbolIcon.numberForeground': s.number,
    'symbolIcon.moduleForeground': s.type,
    'symbolIcon.namespaceForeground': s.type,
    'symbolIcon.typeParameterForeground': s.type,
    'symbolIcon.snippetForeground': p.fg2,
    'testing.iconPassed': p.success,
    'testing.iconFailed': p.error,
    'testing.iconErrored': p.error,
    'testing.iconQueued': p.warning,
    'testing.iconSkipped': p.fg2,
    'testing.runAction': p.success,
  };
}

function rule(name, scope, foreground, fontStyle) {
  const settings = {};
  if (foreground) settings.foreground = foreground;
  if (fontStyle !== undefined) settings.fontStyle = fontStyle;
  return { name, scope, settings };
}

function tokenColors(p) {
  const s = p.syntax;
  const a = p.ansi;
  return [
    // ---- Genéricos
    rule('Comment', ['comment', 'punctuation.definition.comment', 'string.comment', 'comment.block.documentation', 'comment.line.double-slash'], s.comment, 'italic'),
    rule('JSDoc / Swift doc tags', ['storage.type.class.jsdoc', 'punctuation.definition.block.tag.jsdoc', 'keyword.other.documentation', 'comment.block.documentation keyword'], s.comment, 'italic bold'),
    rule('JSDoc types & params', ['comment.block.documentation entity.name.type', 'comment.block.documentation variable.other', 'entity.name.type.instance.jsdoc', 'variable.other.jsdoc'], s.comment, 'italic'),
    rule('Variable', ['variable', 'variable.other', 'variable.other.readwrite', 'variable.other.constant', 'variable.parameter', 'meta.definition.variable.name', 'support.variable', 'entity.name.variable', 'variable.other.readwrite.alias'], s.variable),
    rule('Parameter', ['variable.parameter', 'meta.parameters variable', 'variable.parameter.function.swift'], s.variable, 'italic'),
    rule('Keyword', ['keyword', 'keyword.control', 'keyword.other', 'storage', 'storage.type', 'storage.modifier', 'keyword.operator.new', 'keyword.operator.expression', 'keyword.operator.logical.python', 'keyword.operator.wordlike', 'keyword.operator.instanceof', 'keyword.operator.typeof', 'keyword.operator.delete', 'keyword.operator.void', 'keyword.operator.ternary.ts', 'keyword.control.import', 'keyword.control.export', 'keyword.control.from', 'keyword.control.flow', 'keyword.control.conditional', 'keyword.control.loop', 'storage.type.function.arrow', 'keyword.operator.spread'], s.keyword),
    rule('Language variables (this, self, super)', ['variable.language', 'variable.language.this', 'variable.language.self', 'variable.language.super', 'keyword.expressions-and-types.swift', 'variable.language.special.self.swift'], s.keyword, 'italic'),
    rule('Operators & punctuation', ['keyword.operator', 'keyword.operator.assignment', 'keyword.operator.arithmetic', 'keyword.operator.comparison', 'keyword.operator.relational', 'keyword.operator.logical', 'keyword.operator.bitwise', 'keyword.operator.type', 'keyword.operator.type.annotation', 'keyword.operator.optional', 'keyword.operator.rest', 'keyword.operator.definiteassignment', 'punctuation', 'punctuation.separator', 'punctuation.terminator', 'punctuation.accessor', 'punctuation.definition.parameters', 'punctuation.definition.block', 'punctuation.definition.group', 'punctuation.definition.array', 'punctuation.section', 'punctuation.definition.dictionary', 'meta.brace', 'meta.brace.round', 'meta.brace.square', 'meta.brace.curly', 'meta.delimiter', 'punctuation.definition.binding-pattern', 'punctuation.definition.typeparameters', 'punctuation.separator.key-value', 'punctuation.separator.dictionary', 'punctuation.separator.comma'], s.punctuation),
    rule('String', ['string', 'string.quoted', 'string.template', 'string.unquoted', 'punctuation.definition.string', 'string.quoted.double', 'string.quoted.single', 'markup.inline.raw.string'], s.string),
    rule('String escape & interpolation', ['constant.character.escape', 'constant.character', 'string.regexp', 'constant.other.character-class.regexp', 'keyword.operator.quantifier.regexp', 'punctuation.definition.group.regexp', 'constant.other.placeholder'], s.regexp),
    rule('Template expression', ['punctuation.definition.template-expression', 'punctuation.section.embedded', 'punctuation.definition.template-expression.begin', 'punctuation.definition.template-expression.end', 'meta.embedded.line.swift punctuation.section.embedded', 'punctuation.section.embedded.begin.swift', 'punctuation.section.embedded.end.swift'], s.keyword),
    rule('Template expression body', ['meta.template.expression', 'meta.embedded.line.swift', 'source.swift meta.embedded'], s.variable),
    rule('Number & constants', ['constant.numeric', 'constant.language', 'constant.language.boolean', 'constant.language.null', 'constant.language.undefined', 'constant.language.nil', 'constant.other', 'constant.other.color', 'support.constant', 'variable.other.enummember', 'constant.other.enum', 'keyword.other.unit', 'constant.numeric.integer', 'constant.numeric.float', 'constant.language.json', 'constant.other.symbol'], s.number),
    rule('Function', ['entity.name.function', 'support.function', 'meta.function-call entity.name.function', 'meta.function-call.generic', 'variable.function', 'entity.name.function.member', 'meta.function-call support.function', 'entity.name.function.swift', 'support.function.any-method', 'entity.name.method', 'entity.name.function.decorator', 'meta.decorator entity.name.function', 'support.function.builtin', 'entity.name.function.call'], s.function),
    rule('Decorators & attributes', ['meta.decorator', 'punctuation.decorator', 'storage.type.attribute.swift', 'keyword.other.attribute.swift', 'entity.name.function.attribute', 'meta.attribute.swift', 'storage.modifier.attribute.swift'], s.function, 'italic'),
    rule('Type & class', ['entity.name.type', 'entity.name.class', 'entity.name.type.class', 'entity.name.type.interface', 'entity.name.type.alias', 'entity.name.type.enum', 'entity.name.type.struct', 'entity.name.type.protocol', 'entity.name.type.parameter', 'entity.name.type.module', 'entity.name.namespace', 'entity.other.inherited-class', 'support.type', 'support.class', 'support.type.primitive', 'support.type.builtin', 'support.type.swift', 'support.class.swift', 'support.type.object.module', 'entity.name.type.swift', 'entity.name.type.instance', 'storage.type.primitive', 'meta.type.annotation entity.name.type', 'support.class.builtin', 'support.class.component', 'entity.name.type.extension.swift', 'entity.name.type.typealias.swift', 'entity.name.type.associatedtype.swift'], s.type),
    rule('Property', ['variable.other.property', 'variable.other.object.property', 'variable.other.member', 'meta.object-literal.key', 'meta.object-literal.key string', 'support.variable.property', 'support.type.property-name', 'entity.other.attribute-name', 'variable.object.property', 'meta.property-name', 'variable.other.property.swift', 'meta.definition.property entity.name.function', 'entity.name.function.swift meta.property'], s.property),
    rule('Object (receiver)', ['variable.other.object', 'support.variable.object'], s.variable),

    // ---- JS / TS / JSX / TSX
    rule('JSX/HTML tag', ['entity.name.tag', 'meta.tag.sgml', 'entity.name.tag.html', 'entity.name.tag.tsx', 'entity.name.tag.jsx', 'entity.name.tag.js', 'meta.tag.structure', 'entity.name.tag.xml'], s.keyword),
    rule('JSX component', ['support.class.component', 'support.class.component.tsx', 'support.class.component.jsx', 'entity.name.tag.component', 'entity.name.tag.custom'], s.type),
    rule('Tag punctuation', ['punctuation.definition.tag', 'punctuation.definition.tag.begin', 'punctuation.definition.tag.end', 'punctuation.definition.tag.html', 'punctuation.definition.tag.xml'], s.punctuation),
    rule('JSX text', ['meta.jsx.children', 'meta.jsx.children.tsx', 'meta.jsx.children.js', 'text.html'], s.variable),
    rule('JSX attribute', ['entity.other.attribute-name.jsx', 'entity.other.attribute-name.tsx', 'entity.other.attribute-name.html', 'entity.other.attribute-name.xml'], s.property, 'italic'),
    rule('JSX embedded braces', ['punctuation.section.embedded.begin.tsx', 'punctuation.section.embedded.end.tsx', 'punctuation.section.embedded.begin.jsx', 'punctuation.section.embedded.end.jsx', 'punctuation.section.embedded.begin.js', 'punctuation.section.embedded.end.js'], s.keyword),
    rule('TS type keywords', ['keyword.operator.expression.keyof', 'keyword.operator.expression.typeof', 'keyword.operator.expression.infer', 'keyword.operator.expression.is', 'keyword.operator.expression.as', 'keyword.control.as', 'keyword.control.satisfies', 'storage.type.type', 'storage.type.interface', 'storage.type.enum', 'storage.type.namespace'], s.keyword),
    rule('Import / export names', ['meta.import variable.other.readwrite', 'meta.export variable.other.readwrite', 'variable.other.readwrite.alias'], s.variable),
    rule('Object keys in destructuring', ['meta.object-binding-pattern-variable variable.object.property', 'meta.object.member'], s.property),

    // ---- Swift
    rule('Swift declaration keywords', ['storage.type.function.swift', 'storage.type.class.swift', 'storage.type.struct.swift', 'storage.type.enum.swift', 'storage.type.protocol.swift', 'storage.type.extension.swift', 'storage.type.swift', 'keyword.other.declaration-specifier.swift', 'keyword.other.declaration-specifier.accessibility.swift', 'storage.modifier.swift', 'keyword.control.import.swift', 'keyword.other.import.swift', 'keyword.control.branch.swift', 'keyword.control.loop.swift', 'keyword.control.transfer.swift', 'keyword.control.exception.swift', 'keyword.other.capture-specifier.swift', 'keyword.other.operator.swift'], s.keyword),
    rule('Swift argument labels', ['variable.parameter.function.swift entity.name.function.swift', 'entity.name.function.argument-label.swift', 'variable.other.argument-label.swift', 'support.variable.argument-label.swift', 'entity.name.label.swift', 'variable.parameter.external.swift'], s.property, 'italic'),
    rule('Swift builtin functions', ['support.function.swift', 'support.function.builtin.swift'], s.function),
    rule('Swift # directives', ['keyword.control.import.preprocessor.swift', 'meta.preprocessor.swift', 'keyword.control.preprocessor.swift', 'support.variable.discretionary.swift'], s.number),

    // ---- JSON
    rule('JSON key', ['support.type.property-name.json', 'support.type.property-name.json punctuation.support.type.property-name', 'meta.structure.dictionary.key.json string', 'source.json meta.structure.dictionary.json support.type.property-name.json'], s.property),
    rule('JSON key level 2', ['source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json'], s.type),
    rule('JSON key level 3', ['source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json'], s.function),
    rule('JSON punctuation', ['punctuation.separator.dictionary.key-value.json', 'punctuation.separator.dictionary.pair.json', 'punctuation.separator.array.json', 'punctuation.definition.dictionary.begin.json', 'punctuation.definition.dictionary.end.json', 'punctuation.definition.array.begin.json', 'punctuation.definition.array.end.json'], s.punctuation),

    // ---- YAML
    rule('YAML key', ['entity.name.tag.yaml', 'support.type.property-name.yaml', 'meta.mapping.key.yaml string'], s.property),
    rule('YAML value', ['string.unquoted.plain.out.yaml', 'string.unquoted.plain.in.yaml', 'string.unquoted.block.yaml'], s.string),
    rule('YAML anchors & tags', ['entity.name.type.anchor.yaml', 'variable.other.alias.yaml', 'storage.type.tag-handle.yaml', 'punctuation.definition.anchor.yaml', 'punctuation.definition.alias.yaml', 'keyword.other.directive.yaml'], s.type),
    rule('YAML punctuation', ['punctuation.separator.key-value.mapping.yaml', 'punctuation.definition.block.sequence.item.yaml', 'punctuation.definition.document.yaml', 'entity.other.document.begin.yaml'], s.punctuation),

    // ---- HTML
    rule('HTML doctype', ['meta.tag.metadata.doctype', 'entity.name.tag.doctype', 'meta.tag.sgml.doctype', 'meta.tag.metadata.doctype.html entity.name.tag'], s.comment),
    rule('HTML attribute value', ['meta.attribute string', 'string.quoted.double.html', 'string.quoted.single.html', 'string.unquoted.html'], s.string),
    rule('HTML attribute id/class', ['entity.other.attribute-name.id.html', 'entity.other.attribute-name.class.html'], s.property, 'italic'),
    rule('HTML entities', ['constant.character.entity', 'constant.character.entity.named', 'punctuation.definition.entity'], s.number),

    // ---- CSS / SCSS / Less
    rule('CSS selector tag', ['entity.name.tag.css', 'entity.name.tag.scss', 'entity.name.tag.less', 'entity.name.tag.wildcard.css'], s.keyword),
    rule('CSS class selector', ['entity.other.attribute-name.class.css', 'entity.other.attribute-name.class.scss', 'entity.other.attribute-name.class.less', 'entity.other.attribute-name.parent-selector-suffix.css'], s.function),
    rule('CSS id selector', ['entity.other.attribute-name.id.css', 'entity.other.attribute-name.id.scss', 'entity.other.attribute-name.id'], s.number),
    rule('CSS pseudo', ['entity.other.attribute-name.pseudo-class.css', 'entity.other.attribute-name.pseudo-element.css', 'entity.other.attribute-name.pseudo-class', 'entity.other.attribute-name.pseudo-element', 'punctuation.definition.entity.css'], s.type, 'italic'),
    rule('CSS property', ['support.type.property-name.css', 'support.type.property-name.scss', 'support.type.property-name.less', 'support.type.vendored.property-name.css', 'meta.property-name.css'], s.property),
    rule('CSS value', ['support.constant.property-value.css', 'support.constant.property-value.scss', 'meta.property-value.css', 'support.constant.font-name.css', 'support.constant.vendored.property-value.css'], s.string),
    rule('CSS numbers & colors', ['constant.numeric.css', 'keyword.other.unit.css', 'constant.other.color.rgb-value.hex.css', 'support.constant.color.w3c-standard-color-name.css', 'constant.numeric.scss', 'keyword.other.unit.scss'], s.number),
    rule('CSS functions', ['support.function.misc.css', 'support.function.transform.css', 'support.function.calc.css', 'support.function.gradient.css', 'support.function.url.css', 'support.function.color.css', 'support.function.var.css'], s.function),
    rule('CSS custom properties & SCSS variables', ['variable.css', 'variable.argument.css', 'variable.scss', 'variable.less', 'support.type.custom-property.name.css', 'support.type.custom-property.css', 'variable.other.custom-property.css'], s.variable),
    rule('CSS at-rules', ['keyword.control.at-rule', 'keyword.control.at-rule.css', 'keyword.control.at-rule.media.css', 'keyword.control.at-rule.import.css', 'punctuation.definition.keyword.css', 'keyword.control.at-rule.include.scss', 'keyword.control.at-rule.mixin.scss'], s.keyword),
    rule('CSS important', ['keyword.other.important.css', 'keyword.other.important'], s.number, 'bold'),
    rule('CSS punctuation', ['punctuation.section.property-list.begin.bracket.curly.css', 'punctuation.section.property-list.end.bracket.curly.css', 'punctuation.separator.key-value.css', 'punctuation.terminator.rule.css', 'punctuation.definition.group.begin.css', 'punctuation.definition.group.end.css', 'punctuation.separator.list.comma.css'], s.punctuation),

    // ---- Markdown
    rule('Markdown heading', ['markup.heading', 'entity.name.section.markdown', 'markup.heading.markdown', 'heading.1.markdown', 'heading.2.markdown', 'heading.3.markdown'], s.keyword, 'bold'),
    rule('Markdown heading punctuation', ['punctuation.definition.heading.markdown'], s.keyword),
    rule('Markdown bold', ['markup.bold', 'markup.bold.markdown', 'punctuation.definition.bold.markdown'], s.number, 'bold'),
    rule('Markdown italic', ['markup.italic', 'markup.italic.markdown', 'punctuation.definition.italic.markdown'], s.property, 'italic'),
    rule('Markdown strikethrough', ['markup.strikethrough'], s.punctuation, 'strikethrough'),
    rule('Markdown inline code', ['markup.inline.raw', 'markup.inline.raw.markdown', 'markup.fenced_code.block.markdown punctuation.definition', 'punctuation.definition.raw.markdown', 'fenced_code.block.language'], s.string),
    rule('Markdown code block', ['markup.fenced_code', 'markup.raw.block'], s.variable),
    rule('Markdown link text', ['string.other.link.title.markdown', 'string.other.link.description.markdown', 'meta.link.inline.markdown string.other.link', 'meta.image.inline.markdown string.other.link'], s.function),
    rule('Markdown link url', ['markup.underline.link', 'markup.underline.link.markdown', 'markup.underline.link.image.markdown', 'meta.link.inline.markdown markup.underline.link'], s.type, 'underline'),
    rule('Markdown link punctuation', ['punctuation.definition.link.title.begin.markdown', 'punctuation.definition.link.title.end.markdown', 'punctuation.definition.metadata.markdown', 'punctuation.definition.link.markdown'], s.punctuation),
    rule('Markdown quote', ['markup.quote', 'markup.quote.markdown', 'punctuation.definition.quote.begin.markdown'], s.comment, 'italic'),
    rule('Markdown list marker', ['punctuation.definition.list.begin.markdown', 'beginning.punctuation.definition.list.markdown', 'beginning.punctuation.definition.quote.markdown', 'markup.list.unnumbered punctuation', 'markup.list.numbered punctuation'], s.keyword),
    rule('Markdown separator', ['meta.separator.markdown', 'punctuation.definition.thematic-break.markdown'], s.punctuation),
    rule('Markdown table', ['punctuation.definition.table.markdown', 'punctuation.separator.table.markdown'], s.punctuation),
    rule('Markdown front matter', ['meta.embedded.block.frontmatter', 'markup.raw.yaml.front-matter'], s.variable),

    // ---- Shell
    rule('Shell variable', ['variable.other.normal.shell', 'variable.other.special.shell', 'variable.other.positional.shell', 'variable.other.bracket.shell', 'punctuation.definition.variable.shell', 'variable.other.assignment.shell', 'variable.parameter.positional.shell'], s.property),
    rule('Shell builtin & command', ['support.function.builtin.shell', 'entity.name.command.shell', 'entity.name.function.call.shell', 'support.function.external.shell'], s.function),
    rule('Shell keyword', ['keyword.control.shell', 'storage.type.function.shell', 'keyword.other.shell', 'storage.modifier.shell'], s.keyword),
    rule('Shell option', ['constant.other.option.shell', 'constant.other.option', 'string.unquoted.argument.shell constant.other.option'], s.type),
    rule('Shell operators', ['keyword.operator.pipe.shell', 'keyword.operator.redirect.shell', 'keyword.operator.logical.shell', 'keyword.operator.heredoc.shell', 'punctuation.separator.statement.semicolon.shell'], s.punctuation),
    rule('Shell interpolation', ['punctuation.definition.evaluation.backticks.shell', 'punctuation.definition.subshell.shell', 'string.interpolated.dollar.shell punctuation', 'string.interpolated.backtick.shell'], s.keyword),
    rule('Shell shebang', ['comment.line.number-sign.shebang', 'comment.line.shebang', 'keyword.other.shebang'], s.comment, 'italic'),

    // ---- Diff / Git
    rule('Diff inserted', ['markup.inserted', 'markup.inserted.diff', 'meta.diff.header.to-file', 'punctuation.definition.to-file.diff', 'punctuation.definition.inserted.diff'], p.git.added),
    rule('Diff deleted', ['markup.deleted', 'markup.deleted.diff', 'meta.diff.header.from-file', 'punctuation.definition.from-file.diff', 'punctuation.definition.deleted.diff'], p.git.deleted),
    rule('Diff changed', ['markup.changed', 'markup.changed.diff', 'punctuation.definition.changed.diff'], p.git.modified),
    rule('Diff header & range', ['meta.diff.header', 'meta.diff.range', 'meta.diff.index', 'meta.separator.diff', 'meta.diff.range.unified', 'meta.diff.header.git'], s.type),
    rule('Git commit/rebase', ['constant.sha.git-rebase', 'support.function.git-rebase', 'keyword.other.git-commit'], s.number),
    rule('Markup ignored / untracked', ['markup.ignored', 'markup.untracked'], s.comment),

    // ---- Invalid
    rule('Invalid', ['invalid', 'invalid.illegal'], p.error),
    rule('Deprecated', ['invalid.deprecated'], p.warning, 'strikethrough'),

    // ---- Formatting (sempre por último)
    rule('Bold', ['markup.bold', 'strong'], undefined, 'bold'),
    rule('Italic', ['markup.italic', 'emphasis'], undefined, 'italic'),
    rule('Underline', ['markup.underline'], undefined, 'underline'),
  ];
}

function semanticTokenColors(p) {
  const s = p.syntax;
  return {
    variable: s.variable,
    'variable.readonly': s.variable,
    'variable.defaultLibrary': s.type,
    parameter: { foreground: s.variable, italic: true },
    property: s.property,
    'property.readonly': s.property,
    enumMember: s.number,
    function: s.function,
    method: s.function,
    'function.defaultLibrary': s.function,
    class: s.type,
    interface: s.type,
    struct: s.type,
    enum: s.type,
    type: s.type,
    typeParameter: s.type,
    namespace: s.type,
    keyword: s.keyword,
    selfKeyword: { foreground: s.keyword, italic: true },
    decorator: { foreground: s.function, italic: true },
    macro: s.function,
    string: s.string,
    number: s.number,
    regexp: s.regexp,
    comment: { foreground: s.comment, italic: true },
    operator: s.punctuation,
    '*.deprecated': { strikethrough: true },
  };
}

function build(p) {
  const c = colors(p);
  return {
    $schema: 'vscode://schemas/color-theme',
    name: p.name,
    type: p.type,
    semanticHighlighting: true,
    colors: c,
    tokenColors: tokenColors(p),
    semanticTokenColors: semanticTokenColors(p),
  };
}

for (const [p, file] of [[dark, 'toski-dark-color-theme.json'], [light, 'toski-light-color-theme.json']]) {
  const out = path.join(root, 'themes', file);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, JSON.stringify(build(p), null, 2) + '\n');
  const t = build(p);
  const scopes = new Set(t.tokenColors.flatMap((r) => r.scope));
  console.log(`${file}: ${Object.keys(t.colors).length} workbench colors, ${t.tokenColors.length} rules, ${scopes.size} scopes, ${Object.keys(t.semanticTokenColors).length} semantic`);
}
